LongName: Villanova University
Description: Villanova University 
ID: 10309
AddressLine1: 800 E. Lancaster Ave
City: Villanova
Country: United States
State: Pennsylvania
Zipcode: "19085"
Latitude: 40.04
Longitude: -75.34
