LongName: Louisiana State University Health Sciences Center
Description: Louisiana State University Health Sciences Center

ID: 10304

AddressLine1: 433 Bolivar Street
City: New Orleans

Country: United States
State: Louisiana
Zipcode: 70112

Latitude: 29.958
Longitude: -90.083
