AddressLine1: Science Park 610
City: Amsterdam
Country: NL
Description: Esnet- Amsterdam
ID: 10364
Latitude: 4.95911940
LongName:  Energy Sciences Network - Amsterdam
Longitude: 52.35467570
State: XH
Zipcode: 'AM3:01:031101'
