LongName: Wayne State University
Description: The Wayne State University WSU-GRID_ce2 cluster

ID: 10261
AddressLine1: 5925 Woodward Ave
City: Detroit

Country: United States
State: MI
Zipcode: "48202"

Latitude: 42.363855
Longitude: -83.070494
