LongName: SURF MS4
Description: Computer Science building of the University of XYZ
ID: 10348
AddressLine1: Moreelsepark 48
AddressLine2: Room 101
City: Utrecht
Country: Netherlands
Latitude:
Longitude:
