LongName: Louisiana State University - Deep Bayou
Description: The Louisiana State University Deep Bayou cluster 

ID: 10290

# AddressLine1: Baton Rouge, Louisiana 70803
City: Baton Rouge

Country: United States
State: Louisiana
Zipcode: "70803"

Latitude: 30.4132625
Longitude: -91.182191
