LongName: The College of New Jersey
Description: The The College of New Jersey TCNJ-ELSA cluster 

ID: 10258
AddressLine1: 2000 Pennington Rd, Ewing Township
City: Ewing

Country: United States
State: New Jersey
Zipcode: "08618"

Latitude: 40.259987
Longitude: -74.790909
