LongName: North Carolina State University
Description: HPC group of North Carolina State University
ID: 10308
AddressLine1: 2101 Hillsborough Street
City: Raleigh
Country: USA
State: North Carolina
# Zipcode: 27695
Latitude: 35.78
Longitude: -78.67
