LongName: Louisiana State University LSU_QB2
Description: The Louisiana State University LSU_QB2 cluster 

ID: 10284

# AddressLine1: Baton Rouge, Louisiana 70803
City: Baton Rouge

Country: United States
State: Louisiana
Zipcode: "70803"

Latitude: 30.4132625
Longitude: -91.182191
