AddressLine1: 1340 Administration Ave
City: Fargo
Country: United States
Description: North Dakota State University Center for Computationally Assisted Science and Technology
ID: 10235
Latitude: 46.897592
Longitude: -96.802372
State: ND
Zipcode: '58105'
