# LongName is the expanded name of the site
LongName: Compute Canada Cedar Cluster
# Description is a brief description of your site
Description: Cedar is a heterogeneous cluster suitable for a variety of workloads; it is located at Simon Fraser University.

# If you have an up-to-date local git clone, fill ID with the output from `bin/next_site_id`
# Otherwise, leave it blank and we will fill in the appropriate value for you.
ID: 10281
AddressLine1: 2152 Hillside Road
City: Storrs

Country: United States
State: CT
Zipcode: "06269-3046"

Latitude: 41.8084
Longitude: -72.2495

