AddressLine1: Science Park 105
City: Amsterdam
Country: Netherlands
Description: Nikhef is the Dutch National Institute for Subatomic Physics that performs research in particle physics and astroparticle physics. Nikhef provides distributed computing resources to the Dutch National e-Infrastructure, serving various users from high-energy physics to the life sciences and humanities.
ID: 10257
Latitude: 52.3564
LongName: Nikhef
Longitude: 4.9508
State: North Holland
Zipcode: 1098XG
