LongName: Universite catholique de Louvain Ingrid cluster
Description: Ingrid cluster of the Cosmology, Particle Physics and Phenomenology (CP3) institute of the Universite catholique de Louvain
ID: 10283 
AddressLine1: Avenue Theodore Schwann 2
AddressLine2: Batiment DC III
City: Ottignies-Louvain-la-Neuve 
Country: Belgium
State: Brabant Wallon 
Zipcode: 1348 
Latitude: 50.666707
Longitude: 4.623733
