LongName: Purdue University Geddes Kubernetes Cluster
Description: Geddes is a Kubernetes cluster operated by the Research Computing department at Purdue University
ID: 10282
AddressLine1: 155 South Grant St.
# ### AddressLine2 (optional) is the second line of the street address
# # AddressLine2: Room 101
# # City is the city the site is located in
City: West Lafayette

# Country is the country the site is located in
Country: USA
### State (optional) is the state or province the site is located in
State: Indiana
### Zipcode (optional) is the zipcode/postal code of the site
Zipcode: "47907"

# Latitude is the latitude of the site (positive values are in the northern hemisphere)
Latitude: 40.423004
# Longitude is the longitude of the site (positive values are in the eastern hemisphere)
Longitude: -86.910768
