AddressLine1: 2152 Hillside Road
City: Storrs
Country: United States
Description: University of Connecticut at Storrs
ID: 10109
Latitude: 41.777201
LongName: University of Connecticut
Longitude: -72.217941
State: CT
Zipcode: 06269-3046
