---
LongName: Rice University's Center for Research Computing
Description: Rice University's Center for Research Computing
ID: 10314
AddressLine1: 6100 Main Street
City: Houston
Country: United States
State: Texas
Zipcode: "77005"
Latitude: 29.76
Longitude: -95.36
