AddressLine1: 5925 Woodward Ave
City: Detroit
Country: United States
Description: Wayne State cluster accessed through hosted
ID: 10229
Latitude: 42.363855
Longitude: -83.070494
State: MI
Zipcode: '48202'
