LongName: Cybera Openstack Edmonton
Description: RapidAccess cloud in Edmonton 

ID: 10259

City: Edmonton

Country: Canada
State: Alberta
Zipcode: "T5A"

Latitude: 53.555467
Longitude: -113.7728991

